### PR TITLE
Added auto music injection based on https://projectisland.org/music/

### PR DESCRIPTION
**Pull request by hackerncoder**
Please someone else check to see if my code works. I believe it does but I am not that good at differentiation music.

Also, if someone can make some better code. Go ahead! I am not that good at programming something as complicated like this.

~ HackerNCoder

### CODE REVIEW

**Comment by itsmattkc** [comment]
Thank you for the PR, but I don't really think this feature should be in the main branch. Maybe it can be in a fork if you'd like to maintain one.

**Comment by Sunoo** [comment]
To me, it seems like the best way to handle this would just be a piece of documentation on how files line up with tracks.

**Comment by itsmattkc** [comment]
Possibly, or perhaps a package of the HQ music with the files renamed to match the original filenames in JUKEBOX.SI.

**Comment by Sunoo** [comment]
That actually sounds ideal. Since in my testing, some of the tracks could really use some trimming at the beginning and end and some volume normalization anyways. That could all be done with that pack. I may take a crack at it myself if I have some free time later.

**Comment by xoascf** [comment]
A couple of years ago I had made a pack of some songs from the game ready to replace.
This is the first version I made (2018), there is already a new improved and more complete version from last year that is going to be released in the future.

If you find it useful, you can download the pack here.

Links: https://amai.ga/ostv1 or https://infomaniac.host/files/ost.php
Password: powerBrick01

**Pull request closed without merging**
